### ISSUE TITLE
[Домашнее задание 1] Проверка Виселицы

### ISSUE THREAD

**Issue by arhostcode** [Tanax-Xt/TheHangmanGame#2]
Привет, круто, что умеешь пользоваться докером, да и код достаточно понятный, давай поправим пару моментов и будет еще лучше.

1. Этот метод получился достаточно громоздким, давай попробуем его еще как то поделить на другие методы и классы
```java
public void run() {
```

2. А не хочешь вынести в конструктор как настройку сессии? 
```java
private final int maxTries = 6;
```

3. Давай рандом вынесем в класс, чтобы его не пересоздавать на каждый вызов метода
```java
Random random = new Random();
```

4. Давай поставим тут какой-нибудь модификатор доступа, package-private обычно лучше не использовать
```java
 Word(String word, boolean isHidden) {
        for (char l : word.toCharArray()) {
            charactersList.add(new Letter((Character) l, isHidden));
        }
    }
```
5. А не хочешь изменить метод так, чтобы он сам прибавлял 1 попытку, а не делать set
```java
session.setCurrentTries(session.getCurrentTries() + 1);
```
6. Кажется эту логику можно вынести и в отдельный класс, либо утильный, либо с состоянием, который будет хранить все эти слова после загрузки и возвращать рандомное
```java
List<String> wordsList;
        try {
            wordsList = Files.lines(Paths.get("src/game/words.txt")).toList();
        } catch (IOException e) {
            e.printStackTrace();
            return "error";
        }
```

**Comment by Tanax-Xt** [comment]
Привет! 
Спасибо за ревью, правки вынес в PR https://github.com/Tanax-Xt/TheHangmanGame/pull/3
Не очень понял по поводу 6 пункта, почему лучше не оставлять в качестве метода класса сессии?
